blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/MrXploisLite/RimModManager/discussions
    about: Ask questions and discuss ideas
  - name: ðŸ“– Wiki
    url: https://github.com/MrXploisLite/RimModManager/wiki
    about: Check the wiki for documentation
